#!/bin/bash

mkdir -p ~/bin # -p: Create this directory path if it doesn't exist, and don't complain if it does. This makes it very useful in scripts where you want to ensure a directory exists without having to check first.

mv your-script ~/bin/your-script
chmod +x ~/bin/your-script # makes your script executable

echo 'export PATH="$HOME/bin:$PATH"' >> ~/.zshrc # Add to your PATH in ~/.zshrc (or ~/.bashrc if using bash)

source ~/.zshrc # reloads your shell